# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QApplication
from PyQt5.QtWidgets import QMainWindow

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(656, 536)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("color: rgb(255, 94, 14);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 150, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.check1 = QtWidgets.QCheckBox(Dialog)
        self.check1.setGeometry(QtCore.QRect(370, 190, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check1.setFont(font)
        self.check1.setObjectName("check1")
        self.check2 = QtWidgets.QCheckBox(Dialog)
        self.check2.setGeometry(QtCore.QRect(190, 190, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check2.setFont(font)
        self.check2.setObjectName("check2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 260, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(True)
        self.label_2.setTabletTracking(False)
        self.label_2.setStyleSheet("background-color: rgb(255, 243, 183);\n"
"border-color: rgb(255, 223, 42);")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.btn_generate = QtWidgets.QPushButton(Dialog)
        self.btn_generate.setGeometry(QtCore.QRect(250, 370, 181, 131))
        self.btn_generate.setStyleSheet("background: rgb(16,36,0);\n"
"background: linear-gradient(90deg, rgba(16,36,0,1) 0%, rgba(172,255,0,0.5914740896358543) 100%);")
        self.btn_generate.setDefault(True)
        self.btn_generate.setFlat(False)
        self.btn_generate.setObjectName("btn_generate")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "генератор паролів"))
        self.check1.setText(_translate("Dialog", "з числами"))
        self.check2.setText(_translate("Dialog", "з буквами"))
        self.label_2.setText(_translate("Dialog", "тут результатl"))
        self.btn_generate.setText(_translate("Dialog", "генератор"))

    def generate(self):
        print("click")



class MainWindow(QtWidget):
    def __init__(self):
        super().__init__(self)
        self.window = Ui_MainWindow()
        self.window.setupUi()


    def geherate(self):
        print("123")



app = QApplication([])
main = MainWindow
main.show
app.exec_()


main = MainWindow()















